### ISSUE TITLE
Air Resistance

### ISSUE THREAD

**Issue by simonbw** [simonbw/pod-racer#2]
We should do aerodynamics simulation on pods.

**Comment by michaelwiktorek** [comment]
Working on porting aero stuff from the C++

**Comment by simonbw** [comment]
Ok, I started that too somewhere. I didn't get anywhere.

**Comment by michaelwiktorek** [comment]
I have a version of aerodynamics working, but they don't feel quite right.

**Comment by michaelwiktorek** [comment]
Pushed the latest aero stuff.

**Comment by michaelwiktorek** [comment]
I think we figured this out pretty well. Closing.
