### ISSUE TITLE
Racer Flaps

### ISSUE THREAD

**Issue by michaelwiktorek** [simonbw/pod-racer#7]
We need to add braking/control flaps to the racer.

**Comment by michaelwiktorek** [comment]
Need to figure out getting analog values from gamepad triggers

**Comment by simonbw** [comment]
I believe `navigator.getGamepads()[0].buttons[8].value` will return the analog value of a button that may or may not be a trigger. I don't remember the indexes of all of them. We should modify IO.coffee to handle this.
